name: Submission Fundamental iOS

options:
  deploymentTarget:
      iOS: "15.5"

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    exactVersion: 5.7.1
    revision: bc268c28fb170f494de9e9927c371b8342979ece
  RealmSwift:
    url: https://github.com/realm/realm-swift
    branch: master
    revision: 752f8ae418f97c7e90c2c83ebeeb534c0357df4d

targets:
  Submission Fundamental iOS:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    sources:
      - Submission Fundamental iOS
    dependencies:
      - package: Alamofire
      - package: RealmSwift
      # - package: RealmCore
        # product: RealmDatabase
    info:
      path: /Users/900539/Desktop/DicodingiOS/Submission Fundamental iOS/File System/Info.plist
      properties:
        API_KEY: e2037d96ffc84a45b3d9b74e9e3d5fea
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: NO
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication: [
              { 
                UISceneConfigurationName: Default Configuration,
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
              }
            ]
        UIApplicationSupportsIndirectInputEvents: YES    
        LD_RUNPATH_SEARCH_PATHS: [
          "$(inherited)",
          "@executable_path/Frameworks"
        ]
        ENABLE_BITCODE: NO
        # https://stackoverflow.com/questions/30722606/what-does-enable-bitcode-do-in-xcode-7
        SWIFT_USE_INTEGRATED_DRIVER: NO
        # https://stackoverflow.com/questions/74417530/xcode-14-slow-incremental-builds
    settings:
      GENERATE_INFOPLIST_FILE: YES
      CURRENT_PROJECT_VERSION: 1
      TARGETED_DEVICE_FAMILY: 1,2
      MARKETING_VERSION: 1.0
      PRODUCT_BUNDLE_IDENTIFIER: com.mohammadazri.Submission-Fundamental-iOS
      SWIFT_VERSION: 5.0

      # Automatic Signing
      # CODE_SIGN_STYLE: Automatic
      # DEVELOPMENT_TEAM: PKLN85RDQ6

      # Manual Signing
      CODE_SIGN_STYLE: Manual
    postBuildScripts:
      - name: Run Script Swiftlint
        script: |
          if [[ "$(uname -m)" == arm64 ]]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi

schemes:
  Submission Fundamental iOS:
    build:
      targets:
        Submission Fundamental iOS: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      postActions:
        - settingsTarget: Submission Fundamental iOS